jsonFiles/H27zf8ARmhnv4HBA.json

Create register json

---

jsonFiles/OvKSKOmUZ9ksEr98.json

更新
- 員工報到資料 ( jsonFiles )
issue
- #7

[新增] 員工報到資料

---

jsonFiles/tpNyT8Y60G1pSlOQ.json

新增員工Vito報到資料

---

jsonFiles/trVR2NGjE343jGN7.json

add JSON file
工號：trVR2NGjE343jGN7
#12

add JSON file (trVR2NGjE343jGN7)

---

jsonFiles/Ajg9d62q3cAsiqRP.json

工號： Ajg9d62q3cAsiqRP
issue : #19

新增員工EmptyWu報到

---

jsonFiles/4t9nxyeRphB98al2.json

新增員工Zhang報到

---

jsonFiles/hn6v7IpzEinYVf3N.json

Pei Ying報到資訊

---

jsonFiles/PWjBSJtGsNX1Pv5O.json

工號： PWjBSJtGsNX1Pv5O
issue : #24

新增員工DoubleC報到資料

---

jsonFiles/OrUxKQZ0rzi0YnvJ.json

工號：OrUxKQZ0rzi0YnvJ
issue: #29

Add my new data

---

jsonFiles/N5Bjl6Y9z3fxirID.json

新增 N5Bjl6Y9z3fxirID.json

---

jsonFiles/AJxKh0RnC122rS28.json

工號 : AJxKh0RnC122rS28
issue : #51

新增員工Carrie資料

---

jsonFiles/UkJguPrFpP9cv9mA.json

New staff Json

---

jsonFiles/alTC4PuX7LAPiCer.json

不知道有沒有做對，先試試看再說
我的工號 : alTC4PuX7LAPiCer
issue：[#62](https://github.com/hexschool/escape-onBoardProject/issues/62)

新增員工 zaii 報到資料

---

jsonFiles/BrCde7f7xlZoTv3b.json

add: new staff BrCde7f7xlZoTv3b
#109

add newmember

---

jsonFiles/iwNQm5gHg0cHcshY.json

Update jsonFiles issue#86

---

jsonFiles/irDv9x873uhYRRFT.json

新增員工 json 檔

---

jsonFiles/UbgVo6f0IAhpchgc.json

工號： UbgVo6f0IAhpchgc
issue: #92

UbgVo6f0IAhpchgc  check-in

---

jsonFiles/ivaR89SKmhfvYPo5.json

工號：ivaR89SKmhfvYPo5
issue: #107

Add ivaR89SKmhfvYPo5 json

---

jsonFiles/TejU3DQs9ubbtUWf.json

* add zilong json file in `jsonFiles` folder
* 工號：TejU3DQs9ubbtUWf 
* [Issue#116](https://github.com/hexschool/escape-onBoardProject/issues/116)

feat : add zilong json file

---

jsonFiles/h2UbHwv7SepPU3f3.json

新增員工yijun報到資料 #111

---

jsonFiles/1SK0UUS3JArl9gLG.json

工號：1SK0UUS3JArl9gLG
Issue：[#127](https://github.com/hexschool/escape-onBoardProject/issues/127)

新增員工資料 Jamie

---

jsonFiles/Uz2DE89cciBSM1zf.json

[#133](https://github.com/hexschool/escape-onBoardProject/issues/133#issue-1155397649)

set up new personal file

---

jsonFiles/jZbEZ0zohcZBpqCp.json

This change updated JsonFiles to add one record of employee ID for Rachel Chen.

Issue #91 Add one record of employee ID

---

jsonFiles/f5HMin4WUXK5H8Qj.json

新增員工資料 wen

---

jsonFiles/wpF8KkRBs92qe1rS.json

工號：wpF8KkRBs92qe1rS
issue: #143

Add 員工 miyabi 報到資料

---

jsonFiles/W7XPVdSH0oXO2v5a.json

add new json file

---

jsonFiles/8jbh3DZZVNIhUiDE.json

Add json file #163

---

jsonFiles/0grkMm8byv3rG8L6.json

Add jsonFiles

---

jsonFiles/28AmDSM1052fDWYo.json

工號：28AmDSM1052fDWYo
issue : [#129](https://github.com/hexschool/escape-onBoardProject/issues/129#issue-1155381112)

add:Add staff ID

---

jsonFiles/wBOqlxDq7czEHylX.json

工號：wBOqlxDq7czEHylX
issue #180

add: 增加工號 json 檔

---

jsonFiles/1m8lMZVCcmgnvy9K.json

Add new employee info 新增報到員工資料 #124

---

jsonFiles/rLMhTwlQcvAOLixV.json

新增我的資料#178

---

jsonFiles/tgEJGvtvt746vxKf.json

新增個人簡介檔案 # issue

---

jsonFiles/wHbMLtvbO6xoYhxE.json

工號: wHbMLtvbO6xoYhxE
issue: #196

Add 新進員工資料 #196

---

jsonFiles/LVcbhUpWTdjuH9ew.json

工號：LVcbhUpWTdjuH9ew
issue：#147

新增一筆員工家洋報到資訊 

---

jsonFiles/5QnaH42fMgtAf2NW.json

new employee check in
工號：5QnaH42fMgtAf2NW
issue: #168

Updata member data

---

jsonFiles/fCFGNWjuv7Hnt3hM.json

工號: fCFGNWjuv7Hnt3hM
issue: #73

員工報到 - Zoe

---

jsonFiles/1kZkW4XiQFcrcDaZ.json

Issue：[#205](https://github.com/hexschool/escape-onBoardProject/issues/205)

Add onboard info

---

jsonFiles/5uF16XENzEmJr9gy.json

- #184 
- 工號：5uF16XENzEmJr9gy
3Q >w</

add onBoard Data (#184)

---

jsonFiles/2OpOdBZFz49IZGv6.json

新增一筆員工資料 : Vicky Huang
工號 : 2OpOdBZFz49IZGv6
issue : #84

新增員工 Vicky 報到資料

---

jsonFiles/PRu95V0D9GsUlstw.json

工號：PRu95V0D9GsUlstw
issues: #175

Add json file #175

---

jsonFiles/Eti6C4A5SQDsaALj.json

我的功號：Eti6C4A5SQDsaALj
issue：#192

feat: Add jsonFile

---

jsonFiles/WMN642innTBEoAEB.json
package-lock.json

issue [#218](https://github.com/hexschool/escape-onBoardProject/issues/218)

feat(jsonFiles): add ${member}.json

---

jsonFiles/tjz1yBMZmPPvNkmV.json

Create new worker

---

jsonFiles/nmmreaVDYnRwSy60

工號：nmmreaVDYnRwSy60
Issue：#58
增加資料，請求合併

[報到] moite

---

jsonFiles/a1odbJPhP9rBL1Xi.json

- 新增 jsonFiles
員工報到資料
- issue #222

新增員工資料 [藍藍虎鯨]

---

jsonFiles/IC5DoM1rdnyeKl8J.json

工號: IC5DoM1rdnyeKl8J
issue: [#200](https://github.com/hexschool/escape-onBoardProject/issues/200)

Add json file

---

jsonFiles/meOkMNwamcWSXS3X.json

工號：meOkMNwamcWSXS3X
issue:#231

新進員工資料0305_v7

---

jsonFiles/OG4MRCu7njgF8pFD.json

新成員報到
工號: OG4MRCu7njgF8pFD
issue: #234

Update new member on board

---

jsonFiles/gDhuTRSr9vKhwQWD.json

- 新增 jsonFiles：gDhuTRSr9vKhwQWD.json
- issues：[#241](https://github.com/hexschool/escape-onBoardProject/issues/241#issue-1160551876)

新進人員 Allen 報到 #gDhuTRSr9vKhwQWD

---

jsonFiles/X2W5iriPsE3uy06N.json

Create a member json file

---

jsonFiles/GsItxyrNEXy8uXeu.json

工號: GsItxyrNEXy8uXeu
issue: #246

Add member jsonFiles

---

jsonFiles/52UspDU4KeloYFTF.json

員工報到 : 52UspDU4KeloYFTF

---

jsonFiles/z8p5kEU1qXQ8jeyB.json

工號: z8p5kEU1qXQ8jeyB
issue: #215

add 工號json檔

---

jsonFiles/V7dF6jNcBZyUk0kb.json

工號：V7dF6jNcBZyUk0kb
issue：#171

Add personnel information

---

jsonFiles/IAyqnx6ydzj4sATW.json

工號: IAyqnx6ydzj4sATW
issue tag: https://github.com/hexschool/escape-onBoardProject/issues/266

Register a new member - 新進人員報到

---

jsonFiles/OZJq5e7ZRG7pxOgu.json

Hello~ Hexschool
This is EricHuang #221
Please check it
thanks

feat: Eric Huang finished 1st commit

---

jsonFiles/9urEB604FsjpBkwL.json

工號：9urEB604FsjpBkwL
issue：https://github.com/hexschool/escape-onBoardProject/issues/271

新增我的個人資料 #271

---

jsonFiles/UlpFKCvrGI1HjA2U.json

工號：UlpFKCvrGI1HjA2U
issue：#238

新增我的資料 #238

---

jsonFiles/bp6UV0okkk7gKfjo.json

新增員工報到資料 #248

---

jsonFiles/pdxQK016lWSmjJ7O.json

工號:sDaFdDAa7v7sVtP8
issue: #283

add: 增加新進人員 andersonshen 檔案

---

jsonFiles/fKImRDlhyPr7lYSs.json

Issue: #287 
Add member id fKImRDlhyPr7lYSs json file.

Add a new member json file

---

jsonFiles/cvHDoGM3WCAIsTYI.json

add new employee #293
cvHDoGM3WCAIsTYI.json

add new employee #293

---

jsonFiles/w15Oy3Y8gBjk1wEy.json

issue:#315
工號：w15Oy3Y8gBjk1wEy

增加三隻小貓報到資料

---

jsonFiles/e8Bge3C1Nn4lDLJ4.json

Add new employee json file #317

---

jsonFiles/aPWgk5z1trpAyeXX.json

工號：aPWgk5z1trpAyeXX
issue:#321

增加員工Rowan報到

---

jsonFiles/ssfp4rdhm5ZZ6wBV.json

增加 #325 Abby 員工

---

jsonFiles/haJN82Igc4V4VXXP.json

Add Jules #327

---

jsonFiles/lVJDFhTb52fdZKxD.json

Add new member
